name: "productive-box"
author: "johnnymdoubleu"
description: "Are you an early 🐤 or a night 🦉? Let's check out in gist"
branding:
  icon: "activity"
  color: "blue"
runs:
  using: "node20"
  main: "dist/index.js"
            
